<template lang="pug">

  #app
    .banner
      img(src="https://vuejs.org/images/logo.png" width="100" alt="vue" class="logo")
      h1 Welcome to Vue.js
    .bottom
      | To get started, edit <code>./src/components/App.vue</code> and save to reload.
      br
      span.fade
        Checkout <code>./README.md</code> for more usages.
    headline SDF
    p
      | See <a href="/styleguide/">/styleguide</a> for autogenerated styleguide.
    p 
      | Edit src/components/App.css – styleguide should get re-generated then (has no auto-reload though).


</template>





<script>

import headline from './atomic/headline/'

  export default {
    name: 'app',
    components: {
      headline
    },

  }









// TRYING autoimport SHRUG


// var raw_component_list = require('./atomic/all_components.json')

// // console.log( raw_component_list.json_list[0]["name"] )

// var tempobj = [ { "name": "blah" }, { "name": "blah2" } ]

// // console.log(tempobj[1]["name"])

// // tempobj.push({"name": "something"})

// // tempobj.forEach( function callback(currentValue, index, array) {
// //     console.log(currentValue["name"])
// // });


// raw_component_list.json_list.forEach ( function callback(currentValue, index, array) {
//   tempobj.push({"name": currentValue["name"]})
//   var currentValue["name"] = 'whut';
// });


// tempobj.forEach( function callback(currentValue, index, array) {
//     console.log(currentValue["name"])
// });




// raw_component_list.json_list.forEach( function ( component ) {
//   console.log(component.name)
// })


// var all_components = { list: raw_component_list }

// console.log(all_components.list)

// console.log(all_components);

// all_components.list.forEach( function ( component ) {
//   // var component_path = './atomic/' + component = '/'
//   // import component from './atomic/headline/'
//   console.log(this)
//   var temp_object = { name: component}
//   console.log(temp_object.component)
// })

</script>





<!-- CSS libraries -->
<style src="normalize.css/normalize.css"></style>

<!-- Global CSS -->
<style>

@import "App.css"

</style>

<!-- Scoped component css -->
<!-- It only affect current component -->
<style scoped>
  #app {
    text-align: center;
  }

  #app h1 {
    color: #2c3e50;
    font-weight: 300;
    margin: 0;
  }

  .banner {
    height: 200px;
    background-color: #f6f6f6;
    padding: 50px 10px;
  }

  .bottom {
    padding: 80px 10px;
    font-size: 24px;
    font-weight: 300;
  }

  .fade {
    font-size: 14px;
  }

  .logo {
    animation: spin 4s 1s infinite linear
  }

  @keyframes spin {
    from {transform:rotate(0deg);}
    to {transform:rotate(360deg);}
  }
</style>
